services:
  - type: web
    name: cnn-api
    env: python
    rootDir: cnn_api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000

  - type: web
    name: fusion-api
    env: python
    rootDir: fusion_api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10001

  - type: web
    name: gboost-api
    env: python
    rootDir: gboost_api
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10002
